export enum JobTitle {

  SALON_MANAGER = 'SALON_MANAGER',

  RECEPTIONIST = 'RECEPTIONIST',

  HAIR_STYLIST = 'HAIR_STYLIST',

  COLORIST = 'COLORIST',

  BARBER = 'BARBER',

  ASSISTANT = 'ASSISTANT'
}