export enum ToneLevel {

  LEVEL_1_BLACK = 'LEVEL_1_BLACK',

  LEVEL_2_VERY_DARK_BROWN = 'LEVEL_2_VERY_DARK_BROWN',

  LEVEL_3_DARK_BROWN = 'LEVEL_3_DARK_BROWN',

  LEVEL_4_MEDIUM_BROWN = 'LEVEL_4_MEDIUM_BROWN',

  LEVEL_5_LIGHT_BROWN = 'LEVEL_5_LIGHT_BROWN',

  LEVEL_6_DARK_BLONDE = 'LEVEL_6_DARK_BLONDE',

  LEVEL_7_MEDIUM_BLONDE = 'LEVEL_7_MEDIUM_BLONDE',

  LEVEL_8_LIGHT_BLONDE = 'LEVEL_8_LIGHT_BLONDE',

  LEVEL_9_VERY_LIGHT_BLONDE = 'LEVEL_9_VERY_LIGHT_BLONDE',

  LEVEL_10_LIGHTEST_BLONDE = 'LEVEL_10_LIGHTEST_BLONDE'
}